cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    enmaki:
      email: enmaki@example.com
      name: enmaki
      password: $2b$12$gzeG8BcC6R6pWS36Skv1/OiNrSRJB/.bkh3ZGPsXabor2z7uwjabW
    sanmaki:
      email: sanmaki@example.com
      name: sanmaki
      password: $2b$12$PSmhIepeMHo/MDA6XeA/7.QqI/Y0.98C923SnnL7G0GMko88sjZD2
